server:
  port: 8080
  contextPath: /
  http2:
    enabled: true

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true

spring:
  profiles:
    include:
      - istio
      - keycloak
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/tenant-security}

tenant:
  defaultRole: ${DEFAULT_ROLE:owner}
